// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eogrdrwudymrollpfaiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvZ3Jkcnd1ZHltcm9sbHBmYWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDc0NTksImV4cCI6MjA2ODY4MzQ1OX0.ga6jkyt29_3H8-jRAqIwvIjCSlDC9uXwfpHN-fez3Ok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});